name: Trigger Private Firefox Core

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Trigger reason'
        required: false
        default: 'Manual trigger'
  
  # Optional: schedule để test auto-trigger
  # schedule:
  #   - cron: '0 */6 * * *'  # Mỗi 6 giờ

jobs:
  trigger-private:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Private Repo Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          script: |
            const owner = '${{ secrets.PRIVATE_REPO_OWNER }}';
            const repo = '${{ secrets.PRIVATE_REPO_NAME }}';
            
            console.log(`Triggering workflow in ${owner}/${repo}...`);
            
            try {
              await github.rest.actions.createWorkflowDispatch({
                owner: owner,
                repo: repo,
                workflow_id: 'firefox-service.yml',
                ref: 'main',
                inputs: {
                  trigger_source: 'public-repo',
                  trigger_time: new Date().toISOString()
                }
              });
              
              console.log('✅ Successfully triggered private workflow!');
            } catch (error) {
              console.error('❌ Failed to trigger private workflow:', error.message);
              throw error;
            }
      
      - name: Log Trigger Info
        run: |
          echo "🔄 Trigger completed at $(date)"
          echo "Reason: ${{ github.event.inputs.reason || 'Auto-trigger' }}"
